### ISSUE TITLE
WebSocket Close operation failures are not reported

### ISSUE THREAD

**Issue by manuranga** [ballerina-platform/module-ballerina-http#59]
Errors occurred during WebSocket close operation such as time-outs are not reported. 
This issue was discovered during #50 when the such issues started getting reported.

Please also create an integration (or unit) test to cover this scenario, because it's not currently covered.

**Comment by kalaiyarasiganeshalingam** [comment]
@Bhashinee 
we need to improve the [addError](https://github.com/ballerina-platform/module-ballerina-http/pull/58/files#diff-a003db41d9c1b74c0e4377ee18132004R120) method with appropriate action and implement an integration test to cover this scenario
